[package]
name = "songmaster-rs"
version = "0.1.0"
authors = ["Kyle Strohbeck <kyles@callbox.com>"]
edition = "2018"

[dependencies]
image = "0.21"
itertools = "0.8"
lazy_static = "1.2"
regex = "1.1"

[dev-dependencies]
tempfile = "3.0"
