[package]
name = "songmaster-rs"
version = "0.1.0"
authors = ["Kyle Strohbeck <kyles@callbox.com>"]
edition = "2018"

[dependencies]
id3 = "0.2"
image = "0.21"
lazy_static = "1.2"
regex = "1.1"
yaml-rust = "0.4"

[dev-dependencies]
tempfile = "3.0"
