[package]
name = "songmaster-rs"
version = "0.1.0"
authors = ["Kyle Strohbeck <kstrohbeck@gmail.com>"]
edition = "2018"

[dependencies]
id3 = "0.3.0"
image = "0.21"
indicatif = "0.11.0"
lazy_static = "1.2"
once_cell = "0.2.2"
rayon = "1.1.0"
regex = "1.1"
serde = { version = "1.0.95", features = ["derive"] }
serde_yaml = "0.8.9"
structopt = "0.2.18"
unicode-normalization = "0.1.8"

[dev-dependencies]
tempfile = "3.0"
matches = "0.1.8"
