[package]
name = "songmaster-rs"
version = "0.1.0"
authors = ["Kyle Strohbeck <kstrohbeck@gmail.com>"]
edition = "2018"

[dependencies]
id3 = "0.2"
image = "0.21"
lazy_static = "1.2"
once_cell = "0.2.2"
regex = "1.1"
serde = { version = "1.0.95", features = ["derive"] }
serde_yaml = "0.8.9"

[dev-dependencies]
tempfile = "3.0"
matches = "0.1.8"
